version: '3.8'

name: firecrawl

x-common-service: &common-service
  build: apps/api
  ulimits:
    nofile:
      soft: 65535
      hard: 65535
  networks:
    - backend
  extra_hosts:
    - "host.docker.internal:host-gateway"

x-common-env: &common-env
  REDIS_URL: redis://redis:6379
  REDIS_RATE_LIMIT_URL: redis://redis:6379
  PLAYWRIGHT_MICROSERVICE_URL: http://playwright-service:3000/scrape
  USE_DB_AUTHENTICATION: "false"
  LOGGING_LEVEL: INFO

  # 🔥 Remove these to fully disable Supabase-based auth:
  SUPABASE_URL: ""
  SUPABASE_ANON_TOKEN: ""
  SUPABASE_SERVICE_TOKEN: ""

services:
  redis:
    image: redis:alpine
    networks:
      - backend
    command: redis-server --bind 0.0.0.0

  playwright-service:
    build: apps/playwright-service-ts
    container_name: firecrawl-playwright
    environment:
      PORT: 3000
    networks:
      - backend
    ports:
      - "3000:3000"

  api:
    <<: *common-service
    container_name: firecrawl-api
    environment:
      <<: *common-env
      HOST: "0.0.0.0"
      PORT: 3002
      FLY_PROCESS_GROUP: app
    depends_on:
      - redis
      - playwright-service
    ports:
      - "3002:3002"
    command: [ "pnpm", "run", "start:production" ]

  worker:
    <<: *common-service
    container_name: firecrawl-worker
    environment:
      <<: *common-env
      FLY_PROCESS_GROUP: worker
    depends_on:
      - redis
      - playwright-service
      - api
    command: [ "pnpm", "run", "workers" ]

networks:
  backend:
    driver: bridge
